name: Deploy Heroku

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requiremenst.txt
          pip install flake8 pytest

      - name: Run tests
        run: make test